name: wrkateedge
description: Reference Implementation of working at the edge
publish_to: 'none'
version: 0.0.1-alpha

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flex_color_scheme: ^7.2.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_hooks: ^0.19.0
  flutter_riverpod: ^2.3.6
  fpdart: ^0.6.0
  freezed: ^2.3.5
  freezed_annotation: ^2.2.0
  google_fonts: ^5.1.0
  hooks_riverpod: ^2.3.6
  intl: any
  numeral: ^2.0.1
  riverpod_annotation: ^2.1.1
  squadron: ^5.1.3
  squadron_builder: ^2.4.1
  loggy: ^2.0.3

dev_dependencies:
  build_runner: any
  custom_lint: any
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_generator: ^2.2.3
  riverpod_lint: ^1.3.2

flutter:
  uses-material-design: true


